version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=${NGINX_HOST}
    ports:
      - 80:80
    restart: always
    networks:
      - frontend
    depends_on:
      - node

  node:
    build:
      context: .
      target: development
    container_name: node
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - frontend
      - backend
    command: npm run dev
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
